# Generated by Django 2.2.3 on 2019-07-25 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastebin', '0005_auto_20190725_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='share_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
