# Generated by Django 2.2.3 on 2019-07-26 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0007_auto_20190726_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='share_to',
            field=models.ManyToManyField(blank=True, related_name='sharedTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
